### ISSUE TITLE
MergeLambda.All creates a function called "merged-0"

### ISSUE THREAD

**Issue by onema** [JetBrains/kotless#41] opened 2020-06-28 05:20 UTC
By default the deployment uses `MergeLambda.All` and when there are more than one endpoint, it generates a function called `merged-0` which says nothing about the actual application I'm deploying. The name should really be the application name. 

For example when using `MergeLambda.None` the following functions and names are created:
- `com-example-helloserverless-hello-serverless-tasks-get`
- `com-example-helloserverless-hello-serverless-overview-get`
- `...`

Ideally when using `MergeLambda.All` the name of the function would be something like
- `com-example-helloserverless`

Using kotless `0.1.5` and `spring-boot-lang` `0.1.5`

**Comment by TanVD** [comment] 2020-07-29 16:37
Fixed by @kodart

**Closed by TanVD** 2020-07-29 16:37 UTC
Labels: bug

**Comment by msiemens** [comment] 2021-02-12 16:07
I seem to have the very same issue with 0.1.7-beta-5. I have a deployment that has both API endpoints as well as scheduled events and the generated function name is _merged-0_

**Comment by msiemens** [comment] 2021-02-12 16:26
Seems like my issue is caused by the scheduled event lambda (generated by `@Scheduled`) gets a name like `71172766` which of course has no common prefix with the other lambdas…
